// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class even_part_sms_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(even_part_sms_added));
        
        string IMigrationMetadata.Id
        {
            get { return "202305011713548_even_part_sms_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
